# Generated by Django 3.0.4 on 2020-04-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='line1',
            new_name='calle1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='line2',
            new_name='calle2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postal_code',
            new_name='codigo_postal',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='provincia',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='reference',
            new_name='referencia',
        ),
    ]
